main/urls.py
from django.urls import path
from main.views import show_home, create_cat_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_cat, delete_cat, create_cat_entry_ajax, create_cat_flutter

app_name = 'main'
urlpatterns = [
    path('', show_home, name='show_home'),
    path('create-cat-entry', create_cat_entry, name='create_cat_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-mood/<uuid:id>', edit_cat, name='edit_cat'),
    path('delete/<uuid:id>', delete_cat, name='delete_cat'),
    path('create-cat-entry-ajax', create_cat_entry_ajax, name='create_cat_entry_ajax'),
    path('create-cat-flutter/', create_cat_flutter, name='create_mood_flutter'),

]

meowpedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

class CatEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    age = models.IntegerField()
    description = models.TextField()
    species = models.CharField(max_length=255)
    colour = models.CharField(max_length=255)

main/forms.py
from django.forms import ModelForm
from main.models import CatEntry
from django.utils.html import strip_tags

class CatEntryForm(ModelForm):
    class Meta:
        model = CatEntry
        fields = ["name", "price", "age", "description", "species", "colour"]

    
    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_price(self):
        price = self.cleaned_data["price"]
        return price 

    def clean_age(self):
        age = self.cleaned_data["age"]
        return age

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

    def clean_species(self):
        species = self.cleaned_data["species"]
        return strip_tags(species)

    def clean_colour(self):
        colour = self.cleaned_data["colour"]
        return strip_tags(colour)

main/views.py
from django.shortcuts import render, redirect, reverse
from main.forms import CatEntryForm
from main.models import CatEntry

from django.http import HttpResponse
from django.core import serializers

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from django.utils.html import strip_tags


@login_required(login_url='/login')
def show_home(request):
    
    context = {
        'npm' : '2306201792',
        'name': request.user.username,
        'class': 'PBP E',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "home.html", context)

def create_cat_entry(request):
    form = CatEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        cat_entry = form.save(commit=False)
        cat_entry.user = request.user
        cat_entry.save()
        return redirect('main:show_home')

    context = {'form': form}
    return render(request, "create_cat_entry.html", context)

@csrf_exempt
@require_POST
def create_cat_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = strip_tags(request.POST.get("price"))
    age = strip_tags(request.POST.get("age"))
    description = strip_tags(request.POST.get("description"))
    species = strip_tags(request.POST.get("species"))
    colour = strip_tags(request.POST.get("colour"))

    user = request.user

    new_cat = CatEntry(
        name=name, price=price,
        age=age, description=description,species=species,colour=colour,
        user=user
    )
    new_cat.save()

    return HttpResponse(b"CREATED", status=201)

def edit_cat(request, id):
    cat = CatEntry.objects.get(pk = id)
    form = CatEntryForm(request.POST or None, instance=cat)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_home'))

    context = {'form': form}
    return render(request, "edit_mood.html", context)

def delete_cat(request, id):
    cat = CatEntry.objects.get(pk = id)
    # Hapus cat
    cat.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_home'))


def show_xml(request):
    data = CatEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = CatEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = CatEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = CatEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


# Auth

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
                user = form.get_user()
                login(request, user)
                response = HttpResponseRedirect(reverse("main:show_home"))
                response.set_cookie('last_login', str(datetime.datetime.now()))
                return response
        else:
            messages.error(request, "Invalid username or password. Please try again.")

    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response



from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse

@csrf_exempt
def create_cat_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        new_cat = CatEntry.objects.create(
            user=request.user,
            name=data["name"],
            price=data["price"],
            age=data["age"],
            description=data["description"],
            species=data["species"],
            colour=data["colour"]
        )

        new_cat.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_cat.html
<div class="relative break-inside-avoid cormorant-garamond-bold">
  <div class="absolute top-2 z-10 left-1/2 -translate-x-1/2 flex items-center -space-x-2 ">
    <div class="w-[3rem] h-8 bg-gradient-to-r from-gray-700 to-gray-400 rounded-md opacity-90"></div>
    <div class="w-[3rem] h-8 bg-gradient-to-r from-gray-700 to-gray-900 rounded-md opacity-90"></div>
  </div>
  <div class="relative top-5 bg-white pb-3 shadow-lg rounded-xl mb-6 break-inside-avoid flex flex-col border-2 border-gray-200 transform hover:scale-105 transition-transform duration-300 ease-in-out">
    <div class="bg-gradient-to-r from-gray-700 to-black text-white p-4 rounded-t-xl border-b-2 border-gray-300">
      <h3 class="font-bold text-2xl mb-1 tracking-wide">{{ cat_entry.name }}</h3>
      <p class="text-gray-300 text-xl">Age: {{ cat_entry.age }} years</p>
      <p class="text-gray-300 text-xl">Species: {{ cat_entry.species }}</p>
    </div>
    <div class="p-6 text-gray-900">
      <p class="font-semibold text-xl mb-3">Description</p> 
      <p class="text-gray-600 leading-relaxed mb-3">{{ cat_entry.description }}</p>
      <p class="font-semibold text-xl mb-3">Colour</p>
      <p class="text-gray-600 leading-relaxed mb-3">{{ cat_entry.colour }}</p>
      <p class="font-semibold text-xl mb-3">Price</p>
      <p class="text-gray-600 leading-relaxed">{{ cat_entry.price }}</p>
    </div>

    <div class="relative top-0 -right-6 flex space-x-2">
      <a href="{% url 'main:edit_cat' cat_entry.pk %}" class="bg-gradient-to-r from-gray-800 to-black hover:bg-black text-white rounded-full p-3 transition duration-300 shadow-lg">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" viewBox="0 0 20 20" fill="currentColor">
          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
        </svg>
      </a>
      <a href="{% url 'main:delete_cat' cat_entry.pk %}" class="bg-gradient-to-r from-gray-800 to-black hover:bg-gray-800 text-white rounded-full p-3 transition duration-300 shadow-lg">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>
</div>

main/templates/card_info.html
<div class="bg-indigo-700 rounded-xl overflow-hidden border-2 border-indigo-800">
    <div class="p-4 animate-shine">
      <h5 class="text-lg font-semibold text-gray-200">{{ title }}</h5>
      <p class="text-white">{{ value }}</p>
    </div>
</div>

main/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Meowpedia</title>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}

<div class="relative w-full min-h-screen bg-cover bg-center" style="background-image: url('{% static 'img/cat1.jpg' %}');">
  <div class="absolute inset-0 bg-black opacity-20"></div>
  
  </div>
  <div class="absolute inset-0 flex items-center justify-center">
    <h1 class="text-white text-7xl md:text-8xl font-regular cormorant-garamond-regular">MEOWPEDIA</h1>
  </div>

  <div class="absolute inset-0 flex items-center justify-center top-[10rem]">
    <h2 class="text-white text-xl md:text-2xl font-regular">Find your Soul, find yourself.</h1>
  </div>
  
  <div class="absolute bottom-12 w-full flex justify-center">
    <a href="#main-content" class="bg-white text-gray-900 px-6 py-2 text-lg font-semibold hover:bg-gray-200  transition">
      Discover More
    </a>
  </div>
</div>

<div id="main-content" class="relative px-4 md:px-8 pb-8 pt-12 min-h-screen bg-gray-100">


  <div class="relative justify-center flex cormorant-garamond-bold">
    <h2 class="text-3xl">Featured</h2>
  </div>


  <div id="cat_entry_cards"></div>

  
  <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
    <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">
          Add New Cat Entry
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="px-6 py-4 space-y-6 form-style">
        <form id="catEntryForm">
          <div class="mb-4">
            <label for="cat_name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" id="cat_name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-gray-700" placeholder="Enter cat's name" required>
          </div>
          <div class="mb-4">
            <label for="cat_price" class="block text-sm font-medium text-gray-700">Price</label>
            <input type="number" id="cat_price" name="price" min="0" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-gray-700" required>
          </div>
          <div class="mb-4">
            <label for="cat_age" class="block text-sm font-medium text-gray-700">Age</label>
            <input type="number" id="cat_age" name="age" min="0" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-gray-700" required>
          </div>
          <div class="mb-4">
            <label for="cat_description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea id="cat_description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-gray-700" placeholder="Describe the cat" required></textarea>
          </div>
          <div class="mb-4">
            <label for="cat_species" class="block text-sm font-medium text-gray-700">Species</label>
            <input type="text" id="cat_species" name="species" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-gray-700" required>
          </div>
          <div class="mb-4">
            <label for="cat_colour" class="block text-sm font-medium text-gray-700">Colour</label>
            <input type="text" id="cat_colour" name="colour" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-gray-700" required>
          </div>
        </form>
      </div>

      <!-- Modal footer -->
      <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
        <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
        <button type="button" id="submitCatEntry" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
      </div>

  </div>
</div>

</div>

  <div class="flex justify-center mb-6">
    <a href="{% url 'main:create_cat_entry' %}" class="bg-black content-center hover:bg-gray-700 text-white rounded-lg font-bold py-2 px-4 mx-2 transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
      Add Cat
    </a>
    <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-black content-center hover:bg-gray-700 mx-2 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
      Add New Cat Entry by AJAX
    </button>
  </div>

<script>
  function addCatEntry() {
    fetch("{% url 'main:create_cat_entry_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#catEntryForm')),
    })
    .then(response => refreshCatEntries())

    document.getElementById("catEntryForm").reset(); 
    document.querySelector("[data-modal-toggle='crudModal']").click();
    return false;
  }

  document.getElementById("catEntryForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addCatEntry();
  })
  
  async function getCatEntries(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshCatEntries() {
    document.getElementById("cat_entry_cards").innerHTML = "";
    document.getElementById("cat_entry_cards").className = "";
    const catEntries = await getCatEntries();
    let htmlString = "";
    let classNameString = "";

    if (catEntries.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[10rem] p-6";
        htmlString = `
            <img src="{% static 'img/sadge.jpg' %}" alt="Sad face" class="w-[20%]"/>
            <p class="text-center text-gray-600 mt-4 text-[2rem]">No Cat has been Registered.</p>
        `;
    }
    else {
        classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full"
        catEntries.forEach((item) => {
          htmlString += `
          <div class="relative break-inside-avoid cormorant-garamond-bold">
            <div class="absolute top-2 z-10 left-1/2 -translate-x-1/2 flex items-center -space-x-2 ">
              <div class="w-[3rem] h-8 bg-gradient-to-r from-gray-700 to-gray-400 rounded-md opacity-90"></div>
              <div class="w-[3rem] h-8 bg-gradient-to-r from-gray-700 to-gray-900 rounded-md opacity-90"></div>
            </div>
            <div class="relative top-5 bg-white pb-3 shadow-lg rounded-xl mb-6 break-inside-avoid flex flex-col border-2 border-gray-200 transform hover:scale-105 transition-transform duration-300 ease-in-out">
              <div class="bg-gradient-to-r from-gray-700 to-black text-white p-4 rounded-t-xl border-b-2 border-gray-300">
                <h3 class="font-bold text-2xl mb-1 tracking-wide">${item.fields.name}</h3>
                <p class="text-gray-300 text-xl">Age: ${item.fields.age} years</p>
                <p class="text-gray-300 text-xl">Species: ${item.fields.species}</p>
              </div>
              <div class="p-6 text-gray-900">
                <p class="font-semibold text-xl mb-3">Description</p> 
                <p class="text-gray-600 leading-relaxed mb-3">${item.fields.description}</p>
                <p class="font-semibold text-xl mb-3">Colour</p>
                <p class="text-gray-600 leading-relaxed mb-3">${item.fields.colour}</p>
                <p class="font-semibold text-xl mb-3">Price</p>
                <p class="text-gray-600 leading-relaxed">${item.fields.price}</p>
              </div>
          
              <div class="relative top-0 -right-6 flex space-x-2">
                <a href="/edit-cat/${item.pk}" class="bg-gradient-to-r from-gray-800 to-black hover:bg-black text-white rounded-full p-3 transition duration-300 shadow-lg">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                  </svg>
                </a>
                <a href="/delete/${item.pk}" class="bg-gradient-to-r from-gray-800 to-black hover:bg-gray-800 text-white rounded-full p-3 transition duration-300 shadow-lg">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                  </svg>
                </a>
              </div>
            </div>
          </div>
            `;
        });
    }
    document.getElementById("cat_entry_cards").className = classNameString;
    document.getElementById("cat_entry_cards").innerHTML = htmlString;
  }
  refreshCatEntries();

  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150); 
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);
  document.getElementById("submitCatEntry").onclick = addCatEntry

 
</script>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-50 sm:px-6 lg:px-0">
  <div class="w-full h-screen grid grid-cols-1 lg:grid-cols-2">

    <div class="hidden lg:block bg-gray-200">
      <div class="h-full w-full bg-cover bg-center" style="background-image: url('{% static 'img/cat3.jpg' %}');"></div>
    </div>

    <div class="flex items-center justify-center w-full h-full bg-white px-8">
      <div class="w-full max-w-md space-y-8">
        <div>
          <h2 class="text-center text-black text-3xl font-extrabold">
            Login to your account
          </h2>
        </div>
        <form class="mt-8 space-y-6" method="POST" action="">
          {% csrf_token %}
          <input type="hidden" name="remember" value="true">
          <div class="rounded-md shadow-sm -space-y-px">
            <div>
              <label for="username" class="sr-only">Username</label>
              <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" placeholder="Username">
            </div>
            <div>
              <label for="password" class="sr-only">Password</label>
              <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" placeholder="Password">
            </div>
          </div>

          <div>
            <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-gray-100 bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
              Sign in
            </button>
          </div>
        </form>

        {% if messages %}
        <div class="mt-4">
          {% for message in messages %}
          {% if message.tags == "success" %}
                <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                    <span class="block sm:inline">{{ message }}</span>
                </div>
            {% elif message.tags == "error" %}
                <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                    <span class="block sm:inline">{{ message }}</span>
                </div>
            {% else %}
                <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                    <span class="block sm:inline">{{ message }}</span>
                </div>
            {% endif %}
          {% endfor %}
        </div>
        {% endif %}

        <div class="text-center mt-4">
          <p class="text-sm text-black">
              Don't have an account yet?
            <a href="{% url 'main:register' %}" class="font-medium text-gray-600 hover:text-gray-900">
              Register Now
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/navbar.html
<nav class="shadow-lg fixed top-0 left-0 z-40 w-screen">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <h1 class="text-2xl font-bold text-center text-white cormorant-garamond-regular"></h1>
        </div>
        <div class="hidden md:flex items-center">
          {% if user.is_authenticated %}
            <span class="text-white mr-4">Catlovers, {{ user.username }}</span>
            <a href="{% url 'main:logout' %}" class="text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300 cormorant-garamond-regular">
              Logout
            </a>
          {% else %}
            <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2 cormorant-garamond-regular">
              Login
            </a>
            <a href="{% url 'main:register' %}" class="text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300 cormorant-garamond-regular">
              Register
            </a>
          {% endif %}
        </div>
        <div class="md:hidden flex items-center">
          <button class="mobile-menu-button">
            <svg class="w-6 h-6 text-white" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
              <path d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
    <!-- Mobile menu -->
    <div class="mobile-menu hidden md:hidden  px-4 w-full md:max-w-full ">
      <div class="pt-2 pb-3 space-y-1 mx-auto">
        {% if user.is_authenticated %}
          <span class="block text-gray-300 px-3 py-2 cormorant-garamond-regular">Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="block text-center bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded transition duration-300 cormorant-garamond-regular">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2 cormorant-garamond-regular">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="block text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300 cormorant-garamond-regular">
            Register
          </a>
        {% endif %}
      </div>
    </div>
    <script>
      const btn = document.querySelector("button.mobile-menu-button");
      const menu = document.querySelector(".mobile-menu");
    
      btn.addEventListener("click", () => {
        menu.classList.toggle("hidden");
      });
    </script>
  </nav>